import * as vscode from "vscode";
import { scanProject } from "../services/projectScanner";

export async function smartReadme() {

    const info = await scanProject();

    if (!info) {
        return;
    }

    const workspaceFolders = vscode.workspace.workspaceFolders;

    if (!workspaceFolders) {
        return;
    }

    const readme = `# ${info.projectName}

## 📖 Description

Describe your project here.

---

## 🚀 Features

- Fast
- Easy to use
- Clean Architecture
- Developer Friendly

---

## 🛠 Tech Stack

- Framework : ${info.framework}
- Language : ${info.language}

---

## 📦 Installation

\`\`\`bash
npm install
\`\`\`

---

## ▶ Usage

\`\`\`bash
npm start
\`\`\`

---

## 📂 Folder Structure

\`\`\`
src/
├── components
├── pages
├── services
├── utils
└── index
\`\`\`

---

## 📦 Dependencies

${info.dependencies.length
? info.dependencies.map(d => `- ${d}`).join("\n")
: "No dependencies detected."}

---

## 🛠 Dev Dependencies

${info.devDependencies.length
? info.devDependencies.map(d => `- ${d}`).join("\n")
: "No dev dependencies detected."}

---

## 📄 License

MIT

---

## 👨‍💻 Author

Your Name

---

⭐ Generated by DevPilot AI
`;

    const uri = vscode.Uri.joinPath(
        workspaceFolders[0].uri,
        "README.md"
    );

    await vscode.workspace.fs.writeFile(
        uri,
        Buffer.from(readme)
    );

    vscode.window.showInformationMessage(
        "Smart README generated successfully 🚀"
    );

}